### ISSUE TITLE
Install anaconda, even when using --no-dask

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ec2#12]
This is low-priority

I sometimes want to manage the workers and scheduler myself, rather than have salt do it.  In these cases I use the nicely provided `--no-dask` flag.  However, I find that I now need to install Anaconda by hand.  It would be nice if Anaconda were installed regardless.

I'm fine for now, it's relatively straightforward to install anaconda from the command line with cssh.

**Comment by danielfrg** [comment]
Should be done in https://github.com/dask/dec2/commit/e890f321e0b63630161a70fe7ad71d750fad977d

**Comment by danielfrg** [comment]
All seams to be working. Closing.
