### ISSUE TITLE
Ensure web UI is visible

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ec2#14]
Running `dscheduler` now also starts up a Bokeh web application to visualize the state of the cluster if Bokeh is installed.  In order to make this web server visible to the outside world we need to tell it the address by which users will refer to it, likely the publicly accessible IP address of the head node.  We can do this by passing the address under the `--host ADDRESS` keyword to dscheduler like so:

```
dscheduler --host EXTERNALLY_VISIBLE_ADDRESS
```

Is this address easily available within the salt configuration file that specifies how to launch the scheduler?

**Comment by danielfrg** [comment]
There is a function (https://github.com/dask/dec2/blob/master/dec2/formulas/salt/system/macros.sls#L1) to get the IP of a role but on EC2 its not possible to get the public ip from inside a node.

**Comment by mrocklin** [comment]
This would be the same address that we deliver to the user when we give them instructions on how to ssh into the head node.

**Comment by koverholt** [comment]
Is it not possible in Bokeh server/Tornado to list an address of `0.0.0.0` or `'*'` for all, similar to a Jupyter notebook server? It seems like the last time I tried this in Bokeh, it needed an explicit network interface to whitelist, but perhaps we could look into this more?

**Comment by mrocklin** [comment]
Way ahead of you.  https://github.com/bokeh/bokeh/pull/4052

Waiting for the next Bokeh release is also a decent option.

**Comment by koverholt** [comment]
Cool 👍

**Comment by danielfrg** [comment]
> This would be the same address that we deliver to the user when we give them instructions on how to ssh into the head node.

Yes, I am working in something right now to upload that information to salt.

**Comment by danielfrg** [comment]
I think https://github.com/dask/dec2/commit/0e2b5d9a095e68a37e9c24151f1714f7a1a20da8 does everything that is needed for this.

**Comment by mrocklin** [comment]
Cool.  Trying this out now.

**Comment by mrocklin** [comment]
I'm still not getting the web ui visible by default.  Does this work for you ?  Perhaps there is something wrong with my local environment.

**Comment by danielfrg** [comment]
Do I have to start another service to get the UI or just `dscheduler`? Whats the port it will be listening to?

I installed bokeh but I am not starting anything else besides `dscheduler` and `dworker`.

**Comment by mrocklin** [comment]
Running `dscheduler` should call out to `bokeh serve ...` using `subprocess.Popen`.  This should open up a web server that hosts at `http://scheduler-host-address:8787/status/`

**Comment by mrocklin** [comment]
I suspect that is maybe because `bokeh` wasn't on the `PATH`.  This might be fixed by https://github.com/dask/distributed/pull/228

**Comment by danielfrg** [comment]
Yes, that was it. Should be fixed now on master. Also added a `dec2 dask-distributed ui` command that opens a browser pointing to the status UI.

**Comment by danielfrg** [comment]
I think this is fixed. Closing for now. Please reopen if not.

**Comment by mrocklin** [comment]
Sounds good.  Checking again now.  Will reopen if there is an issue.

**Comment by mrocklin** [comment]
Confirmed.  Thanks for your help @danielfrg !

**Comment by danielfrg** [comment]
Great!
