### ISSUE TITLE
Increase default open file limit 

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ec2#16]
I find that I need to follow these instructions when using dec2 on larger clusters to increase the open file limit for the ubuntu user.

http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

Notably the section starting `User Level FD Limits`

**Comment by mrocklin** [comment]
@danielfrg do you have the time to ensure that the following file gets the following lines appended to it on startup?

```
/etc/security/limits.conf

ubuntu soft nofile 102400
ubuntu hard nofile 102400
```

**Comment by danielfrg** [comment]
After creating the file is it necessary to reboot the machine for that to take effect?

**Comment by mrocklin** [comment]
No.  It works fine if I close out the terminal session and reenter.

**Comment by mrocklin** [comment]
Also, totally unrelated, but while I'm asking for things I also often find myself typing `sudo apt-get install -y git` pretty often on all of the nodes and `jupyter notebook --ip="*"` on the head node (although presumably there is a safer way).

**Comment by danielfrg** [comment]
Hey @mrocklin, I just made a commit to master that makes all those changes: file limit, installs git (as part of the dask provisioning) and also the jupyter notebook with a subcommand in the cli.

Could you give it a try?

**Comment by mrocklin** [comment]
Playing with things now.  Will be a bit.  So far the open file limit seems to work well.

**Comment by mrocklin** [comment]
Everything looks great.  The web ui and notebook both start up beautifully and operate as expected.  I can run larger clusters without running into open file limits.  

Any thoughts on the following commit printing the relevant addresses to the screen? https://github.com/dask/dec2/commit/bad732afdf78a62de0ecaaa6707f76200d2846a0

By looking at the diff I saw the `dec2 dask-distributed ui` command, which didn't work as expected:

```
mrocklin@notebook:~/workspace/dec2$ dec2 dask-distributed ui
gvfs-open: 52.91.39.215:8787/status: error opening location: Error when getting information for file '/home/mrocklin/workspace/dec2/52.91.39.215:8787/status': No such file or directory
```

However, I'm personally pretty satisfied with just echoing the address to the screen

**Comment by danielfrg** [comment]
I think thats because its missing `http://` in https://github.com/dask/dec2/blob/master/dec2/cli/daskd.py#L171 - If you are ok with just echoing the URL thats probably safer.

**Comment by danielfrg** [comment]
Closing since it looks to be solved now.
