### ISSUE TITLE
VPC support

### ISSUE THREAD

**Issue by spitz-dan-l** [dask/dask-ec2#17]
Hello,

In reading up on Dask.distributed I found out about dec2 as an extremely simple way to spin up a cluster on ec2. However, I'm constrained by the fact that my cluster must reside in a VPC. As far as I can tell it's not possible to do this with the script as-is.

It seems like it shouldn't be too hard to modify it myself to support a VPC though. Any advice much appreciated!

Thanks,
Dan

**Comment by danielfrg** [comment]
It should be straight forward to modify the code here (https://github.com/dask/dec2/blob/master/dec2/ec2.py) to support a VPC. Everything is based on boto3, i think you just need to pass the VPC-ID and subnet ID to the `launch` and `ec2.create_instances`.

If you have a default VPC on your EC2 account I think that by default dec2 will create a cluster using that. That is one of the things that is not particularly easy to test but should not be that hard to do.
