### ISSUE TITLE
windows fix

### ISSUE THREAD

**Issue by artttt** [dask/dask-ec2#18]
found a windows incompatibility in salt.py upload_pillar

The issue is  best described by this...
http://stackoverflow.com/questions/15169101/how-to-create-a-temporary-file-that-can-be-read-by-a-subprocess

below is my modified version of the function that works on windows.

```
def upload_pillar(cluster, name, data):
    import os
    import yaml
    import tempfile

    master = cluster.instances[0].ssh_client
    f = tempfile.NamedTemporaryFile('w',delete = False)
    try:
        yaml.safe_dump(data, f, default_flow_style=False)
        f.close()
        local = f.name
        remote = "/srv/pillar/{}".format(name)
        master.put(local, remote, sudo=True)
    finally:
        os.remove(f.name)
```

**Comment by danielfrg** [comment]
Thanks for the report and fix. It should be fix on master now.

**Comment by artttt** [comment]
that was quick - thanks.
just tested and you have a typo with this line

correct version is

```
f = tempfile.NamedTemporaryFile("w", delete=False)
```

you have

```
f = tempfile.NamedTemporaryFile("w", deleteF=False)
```

**Comment by danielfrg** [comment]
Fixed, thanks.
