### ISSUE TITLE
Smooth experience for dask.distributed

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ec2#3]
Q: Should we deploy dask.distributed by default on creation?

When I run `dec2 dask-distributed` I don't immediately see the next step:

```
(27)mrocklin@workstation:~$ dec2 dask-distributed
Installing scheduler
+---------+--------------+----------+
| Node ID | # Successful | # Failed |
+=========+==============+==========+
| node-0  | 10           | 0        |
+---------+--------------+----------+
Installing workers
+---------+--------------+----------+
| Node ID | # Successful | # Failed |
+=========+==============+==========+
| node-1  | 10           | 0        |
| node-3  | 10           | 0        |
| node-2  | 10           | 0        |
+---------+--------------+----------+
```

This might be friendlier if it would print the address of the head node as in `192.168.0.1:8786`

**Comment by mrocklin** [comment]
OK, so I looked into cluster.yaml and tried the first address but that didn't work.  Is there possibly a security permissions thing that needs to be set?  Should the scheduler be listening on a more accessible port?

After that I decided to go onto the cluster itself.  I used `dec2 ssh 0` and got to the head node (always satisfying), but I then tried `ipython` and found that the default environment wasn't attached to anaconda.  

I then tried `/opt/anaconda/bin/conda install ipython -y` but found that I needed sudo.

Then I did that and all worked well

``` python
In [1]: from distributed import Executor

In [2]: e = Executor('127.0.0.1:8786')

In [3]: %time futures = e.map(lambda x: x + 1, range(1000)); result = e.gather(futures)
CPU times: user 529 ms, sys: 14.6 ms, total: 543 ms
Wall time: 1.23 s
```

I would still prefer to connect to the scheduler from my personal machine if we can make that easy.

I'm not sure how much effort we should spend here; my hope is that a few cosmetic changes here will go a long way.

**Comment by danielfrg** [comment]
Yep, most of that things are on my list.

Deploying dask distributed by default sounds good to me.

The scheduler should be running on the first node, i'll take a look. Port `8786` is ok but the server should be listening on `0.0.0.0` for it to accessible from other hosts. I see something like this when I start one.

```
distributed.scheduler - INFO - Start Scheduler at:         172.31.8.171:9090
```

Servers usually have an `ip` argument same as you have one for `port` for example the Jupyter Notebook: 

```
--port=<Int> (NotebookApp.port)
    Default: 8888
    The port the notebook server will listen on.
--ip=<Unicode> (NotebookApp.ip)
    Default: 'localhost'
    The IP address the notebook server will listen on.
```

So to serve the notebook I started it with: `jupyter notebook --ip=0.0.0.0`

I want to have `dec2 dask-distributed open` that prints the URL and port of the scheduler or maybe even a python interpreter that connects to it, not sure how to do that one yet.

**Comment by danielfrg** [comment]
I see that the `Scheduler` has an [`ip` argument](https://github.com/dask/distributed/blob/master/distributed/scheduler.py#L140) but its not available in the CLI at the moment.

What is happening is that on EC2 its getting the private IP from `eth0`.

**Comment by mrocklin** [comment]
The scheduler listens on all hosts.  The address is prints in the logs is the address that it thinks a user will want (although as you point out in this case it's not the correct address).  This shouldn't matter too much though as long as we give the user the correct publicly accessible address.

**Comment by danielfrg** [comment]
Ok, in that case it should be fine. You can see the logs for the Scheduler at `/var/log/dscheduler.log`, in a cluster i just created i see the workers connected but I still cannot connect from my laptop to it, using the public IP for that node.

**Comment by mrocklin** [comment]
Yeah, that was my experience as well, which seemed odd.  I've definitely
connected to clusters that I spun up in the normal way on EC2 in this same
way before.

**Comment by danielfrg** [comment]
Now `dask.distributed` is installed by default and the scheduler address is printed at the end, let me know if you like how its printed or want to change the message.

I had the issue of having the distributed client be on python 3 and the dask distributed cluster be on python 2, that gave a lot of pickle issues on the scheduler.

Now when I do `e = Executor(...)` it hangs and i just get this on the scheduler logs:

```
$ cat /var/log/dscheduler.log
distributed.scheduler - INFO - Start Scheduler at:          172.31.4.43:8786
distributed.scheduler - INFO -            http at:          172.31.4.43:58474
distributed.core - INFO - Connection from 172.31.4.45:54741 to Scheduler
distributed.scheduler - INFO - Register ('172.31.4.45', 59221)
distributed.core - INFO - Connection from 172.31.4.44:42070 to Scheduler
distributed.scheduler - INFO - Register ('172.31.4.44', 43395)
distributed.core - INFO - Connection from 172.31.4.42:50259 to Scheduler
distributed.scheduler - INFO - Register ('172.31.4.42', 50763)
distributed.core - INFO - Connection from 63.96.220.196:52021 to Scheduler
distributed.core - INFO - Connection from 63.96.220.196:52022 to Scheduler
distributed.core - WARNING - No handler found: register-client
```

Can this be because on the cluster I have the latest from pypi and I am running master on my laptop?

**Comment by mrocklin** [comment]
The message that you're seeing is because of that, yes.  Fortunately I'm now in the process of releasing.  Hold tight.

**Comment by mrocklin** [comment]
distributed is released, though dask isn't yet (slight complication) so simple things will probably be fine but some of the more complex hdfs stuff might not work well yet.

Not sure how to handle the pickle stuff other than by raising better error messages.  It's hard to mix the two runtimes.

**Comment by danielfrg** [comment]
Awesome, I just tested again the connection from my laptop to the cluster using the address that is printed and it worked fine. If you could try again, from git master, that would be great.

```
In [1]: a = '54.175.123.156:8786'

In [2]: from distributed import Executor

In [3]:  e = Executor(a)

In [4]: %time futures = e.map(lambda x: x + 1, range(1000)); result = e.gather(futures)
CPU times: user 246 ms, sys: 19.9 ms, total: 266 ms
Wall time: 1.74 s
```

An error message saying that they are incompatible is good enough for me for the pickle error.

**Comment by mrocklin** [comment]
```
(27)mrocklin@workstation:~$ dec2 up --name mycluster --keyname mrocklin --keypair ~/.ssh/anaconda-cluster.pem
Launching nodes
DEBUG: Checking that keyname 'mrocklin' exists on EC2
DEBUG: Checking that security group 'dec2-default' exists on EC2
DEBUG: Creating 4 instances on EC2
DEBUG: Tagging instance 'i-816b5404'
DEBUG: Tagging instance 'i-806b5405'
DEBUG: Tagging instance 'i-836b5406'
DEBUG: Tagging instance 'i-826b5407'
Checking SSH connection to nodes
DEBUG: Checking ssh connection for 54.165.85.63
DEBUG: Checking ssh connection for 54.174.213.76
DEBUG: Checking ssh connection for 54.172.42.152
DEBUG: Checking ssh connection for 54.174.210.128
+----------------+-----------+
| Node IP        | SSH check |
+================+===========+
| 54.174.210.128 | True      |
| 54.172.42.152  | True      |
| 54.165.85.63   | True      |
| 54.174.213.76  | True      |
+----------------+-----------+
Bootstraping salt master
DEBUG: Running command sudo -S bash -c 'curl -sS -L https://bootstrap.saltstack.com | sh -s -- -M -N stable' on '54.165.85.63'
DEBUG: Running command sudo -S bash -c 'curl -L https://bootstrap.saltstack.com | sh -s -- -M -N -P -L -p salt-api stable' on '54.165.85.63'
DEBUG: Uploading file /home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/dec2/templates/auto_accept.conf to /tmp/.__tmp_copy
DEBUG: Attempt 1/3 of function '__setup_salt_master' failed
DEBUG: Uploading file /home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/dec2/templates/auto_accept.conf to /tmp/.__tmp_copy
DEBUG: Attempt 2/3 of function '__setup_salt_master' failed
DEBUG: Uploading file /home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/dec2/templates/auto_accept.conf to /tmp/.__tmp_copy
DEBUG: Attempt 3/3 of function '__setup_salt_master' failed
ERROR: [Errno 2] No such file or directory: '/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/dec2/templates/auto_accept.conf'
Couldn't setup salt-master settings. Error is above (maybe try again)
(27)mrocklin@workstation:~$ dec2 dask-distributed
Installing scheduler
Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/dec2/cli/main.py", line 20, in start
    cli(obj={})
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/click/core.py", line 1037, in invoke
    return Command.invoke(self, ctx)
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/dec2/cli/dask.py", line 12, in dask
    ctx.invoke(dask_install, filepath=filepath)
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/dec2/cli/dask.py", line 22, in dask_install
    cluster.pepper.local("node-0", "grains.append", ["roles", "dask.distributed.scheduler"])
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/dec2/cluster.py", line 47, in get_pepper_client
    self._pepper.login('saltdev', 'saltdev', 'pam')
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/dec2/libpepper.py", line 298, in login
    'eauth': eauth}).get('return', [{}])[0]
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/site-packages/dec2/libpepper.py", line 132, in req
    f = urlopen(req, context=con)
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/home/mrocklin/Software/anaconda/envs/27/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>
```

**Comment by danielfrg** [comment]
Sorry about that. Its unrelated but to dask.distributed and should be fixed on: https://github.com/dask/dec2/commit/f02b11604d1607dbadf14b19457363d6076a9f8e

**Comment by danielfrg** [comment]
If you installed it in develop mode you might have to reinstall to make the new links work.

**Comment by danielfrg** [comment]
Ok, now after installing `dask.distributed` an python (or ipython if available) shell will be open and connect to the distributed cluster, a variable `e` is available to the user. As usual its working for me but if you could try that would be nice.

**Comment by mrocklin** [comment]
Whoa, that's really smooth!

**Comment by mrocklin** [comment]
Does running `dec2 up` twice create a new cluster and overwrite the previous cluster.yaml file?

**Comment by mrocklin** [comment]
Do the workers have full anaconda or just miniconda installed?

**Comment by mrocklin** [comment]
Thoughts on matching the Python version to the version on the local machine?

**Comment by danielfrg** [comment]
> Does running dec2 up twice create a new cluster and overwrite the previous cluster.yaml file?

Yes. Fixed in https://github.com/dask/dec2/commit/faab32300aa9347c8b40da2ef0d7ee2bf7646ca2

> Do the workers have full anaconda or just miniconda installed?

Just miniconda.

**Comment by danielfrg** [comment]
> Thoughts on matching the Python version to the version on the local machine?

Done in https://github.com/dask/dec2/pull/6
