### ISSUE TITLE
s3fs is not installed by default

### ISSUE THREAD

**Issue by ngcrawford** [dask/dask-ec2#34]
On a vanilla `dask-ec2` cluster I can't read data from s3 using standard `dd.read_csv` syntax. It appears that this is because`s3fs` is not installed.

```
ubuntu@ip-172-31-29-138:~$ ipython
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.3 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import s3fs
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-e035bbfffb37> in <module>()
----> 1 import s3fs

ImportError: No module named s3fs

In [2]: quit()
```

**Comment by ngcrawford** [comment]
I tried to install it myself, but got permissions errors I could not resolve even with `sudo`. Some documentation about how to install (or provision) `dask-ec2` clusters with custom python modules would be most appreciated.

**Comment by ngcrawford** [comment]
Hmmm... so maybe it has to do with this: https://github.com/dask/dask-ec2/issues/32 and I need to make a custom conda environment.

**Comment by mynameisvinn** [comment]
first ssh into master node, then providing correct permissions worked for me.
```
dask-ec2 ssh
sudo chown -R ubuntu /opt/anaconda
conda install -c conda-forge s3fs=0.1.1
```
