### ISSUE TITLE
Failed to install scheduler

### ISSUE THREAD

**Issue by raymondchua** [dask/dask-ec2#39]
Hi, I encountered this error: 
Installing scheduler
+---------+----------------------+-----------------+
| Node ID | # Successful actions | # Failed action |
+=========+======================+=================+
| node-0  | 12                   | 5               |
+---------+----------------------+-----------------+
Failed states for 'node-0'
  file | dscheduler.conf | /etc/supervisor/conf.d//dscheduler.conf | managed: One or more requisite failed: dask.distributed.bokeh-install, dask.distributed.update-pandas
  supervisord | dscheduler-running | dscheduler | running: One or more requisite failed: dask.distributed.scheduler.dscheduler.conf, dask.distributed.bokeh-install, dask.distributed.update-pandas, dask.distributed.scheduler.dscheduler-update-supervisor
  cmd | bokeh-install | /opt/anaconda//bin/conda install bokeh -y -q | run: Command "/opt/anaconda//bin/conda install bokeh -y -q" run
  cmd | update-pandas | /opt/anaconda//bin/conda update pandas | run: Command "/opt/anaconda//bin/conda update pandas" run
  cmd | dscheduler-update-supervisor | /usr/bin/supervisorctl -c /etc/supervisor/supervisord.conf update && sleep 2 | wait: One or more requisite failed: dask.distributed.scheduler.dscheduler.conf

**Comment by raymondchua** [comment]
May I missing something? 
The command I was using is `dask-ec2 up --keyname raymond_NV --keypair raymond_NV.pem `
`Installing scheduler
+---------+----------------------+-----------------+
| Node ID | # Successful actions | # Failed action |
+=========+======================+=================+
| node-0  | 13                   | 4               |
+---------+----------------------+-----------------+
Failed states for 'node-0'
  file | dscheduler.conf | /etc/supervisor/conf.d//dscheduler.conf | managed: One or more requisite failed: dask.distributed.update-pandas
  supervisord | dscheduler-running | dscheduler | running: One or more requisite failed: dask.distributed.scheduler.dscheduler.conf, dask.distributed.update-pandas, dask.distributed.scheduler.dscheduler-update-supervisor
  cmd | update-pandas | /opt/anaconda//bin/conda update pandas | run: Command "/opt/anaconda//bin/conda update pandas" run
  cmd | dscheduler-update-supervisor | /usr/bin/supervisorctl -c /etc/supervisor/supervisord.conf update && sleep 2 | wait: One or more requisite failed: dask.distributed.scheduler.dscheduler.conf
`

**Comment by raymondchua** [comment]
I have tried both python2 and python3 but the issue persists.

**Comment by bschreck** [comment]
I'm also having this same issue

**Comment by raymondchua** [comment]
@bschreck , do you get the exact same error message? I have yet to figure out why.

**Comment by bschreck** [comment]
Yes - But I just figured out why and got it to run. Seems like there's an error with pyopenssl and cryptography: https://github.com/conda/conda/issues/3938

You have to run:

CONDA_SSL_VERIFY=false conda update pyopenssl

before:

conda update pandas

So I went into the salt template at formulas/dask/distributed/init.sls and added the following:


update-pyopenssl:
  cmd.run:
    - name: CONDA_SSL_VERIFY=false {{ install_prefix }}/bin/conda update pyopenssl
    - require:
      - sls: conda

And changed the "update-pandas" block to look like:


update-pandas:
  cmd.run:
    - name: {{ install_prefix }}/bin/conda update pandas
    - require:
      - update-pyopenssl
      - pip: distributed-install

**Comment by bschreck** [comment]
I'll submit a pull request

**Comment by raymondchua** [comment]
Thanks @bschreck . 
Now, I face a different error. :(

Installing scheduler
Traceback (most recent call last):
  File "/home/adas/.local/lib/python3.5/site-packages/dask_ec2/cli/main.py", line 23, in start
    cli(obj={})
  File "/home/adas/.local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/adas/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/adas/.local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/adas/.local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/adas/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/adas/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/adas/.local/lib/python3.5/site-packages/dask_ec2/cli/main.py", line 165, in up
    ctx.invoke(provision, filepath=filepath, anaconda_=anaconda_, dask=dask, notebook=notebook, nprocs=nprocs)
  File "/home/adas/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/adas/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/adas/.local/lib/python3.5/site-packages/dask_ec2/cli/main.py", line 309, in provision
    ctx.invoke(dask_install, filepath=filepath, nprocs=nprocs)
  File "/home/adas/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/adas/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/adas/.local/lib/python3.5/site-packages/dask_ec2/cli/daskd.py", line 61, in dask_install
    response = print_state(output)
  File "/home/adas/.local/lib/python3.5/site-packages/dask_ec2/cli/main.py", line 334, in print_state
    response = response.aggregate_by(field="result")
  File "/home/adas/.local/lib/python3.5/site-packages/dask_ec2/salt.py", line 53, in aggregate_by
    successful = [action for action in inner_values if action[field] == validation]
  File "/home/adas/.local/lib/python3.5/site-packages/dask_ec2/salt.py", line 53, in <listcomp>
    successful = [action for action in inner_values if action[field] == validation]
TypeError: string indices must be integers

**Comment by wadimklincov** [comment]
Your indentation is incorrect. I get the same error if something is on the wrong level. Otherwise it works great.

**Comment by bschreck** [comment]
Yeah I think that happened when I pasted into the github comments

**Comment by raymondchua** [comment]
Thanks.
