### ISSUE TITLE
cannot import name 's3'

### ISSUE THREAD

**Issue by raymondchua** [dask/dask-ec2#41]
Hi,
I manage to run the dask-ec2 up command and manage to ssh into the head node.
I start the ipython and execute the following the command, "from distributed import Client, s3, progress" and got a cannon import name 's3' error. Here is the full stack of error.  

from distributed import Executor, s3, progress
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-c1a0089c91b8> in <module>()
----> 1 from distributed import Executor, s3, progress

ImportError: cannot import name 's3'

**Comment by mrocklin** [comment]
That syntax is old.  Instead use a prefix like the following:

    import dask.dataframe as dd
    df = dd.read_csv('s3://bucket-name/myfiles.*.csv')

http://dask.pydata.org/en/latest/bytes.html

**Comment by raymondchua** [comment]
@mrocklin , so you are saying that the information on the dask-ec2 documentation is incorrect?

![screenshot from 2017-01-04 17-48-51](https://cloud.githubusercontent.com/assets/4645110/21650706/242bb986-d2a6-11e6-83a4-215632154ef9.png)

**Comment by mrocklin** [comment]
Yes, that is old.  Can I interest you in submitting a PR to update this
documentation?

**Comment by raymondchua** [comment]
Thanks, I was going to say I am going to do. But you beat me to it. :)
