### ISSUE TITLE
Jupyter notebook now requires password

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ec2#52]
New versions of jupyter now require this by default.

**Comment by koverholt** [comment]
I think you're seeing this from Jupyter notebook 4.3.0 (see https://github.com/jupyter/notebook/issues/1979) since they enabled notebook server auth by default. This is fixed/improved in notebook 4.3.1, which went into conda `defaults` yesterday.

**Comment by quasiben** [comment]
We should probably have an option for setting the password with a default of dask or jupyter?

**Comment by mrocklin** [comment]
That would work fine for me and would be a big improvement.  Currently the notebook is unusable.  We would probably want to print the password when we print out the jupyter notebook address on the command line.

**Comment by quasiben** [comment]
yup yup
