### ISSUE TITLE
vpc-id and subnet-id options not working

### ISSUE THREAD

**Issue by stumitchell** [dask/dask-ec2#53]
both of them are ignored on EC2.__init__() 

with an error like the following

DEBUG: Searching for default subnet in VPC vpc-d82ebebc
ERROR: There is no default subnet on VPC vpc-d82ebebc, please pass a subne

**Comment by stumitchell** [comment]
https://github.com/dask/dask-ec2/pull/59

**Comment by quasiben** [comment]
Resolved by #60
