### ISSUE TITLE
Place demo notebooks on master node

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ec2#54]
It would be nice to give users a few introductory notebooks to play with when they first arrive.  

One convenient way to do this would be to copy a directory of files from this repository to the head node.

**Comment by quasiben** [comment]
We can do that.  Do you want to put some demo notebooks in an example folder ?  We could pull them from: https://github.com/mrocklin/scipy-2016-parallel and @mrocklin's recent blog post: http://matthewrocklin.com/blog/work/2017/01/12/dask-dataframes 

Doing this would mean needing to keep the examples up to date.  I imagine examples are more likely to be updated in the main repo?

**Comment by mrocklin** [comment]
We no longer keep examples notebooks in the main repository. 

I suggest that we keep notebooks within a directory within this repository, similar to how was done from the scipy 2016 tutorial.  This is something that I can populate and maintain easily in the future.

**Comment by quasiben** [comment]
Great, can you add the notebooks and I'll configure the salt states to clone the repo and add the notebooks server side.  Ideally, you could do this shortly and I'll update #55
