### ISSUE TITLE
Verify no lingering services on EC2

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ec2#62]
Is it possible that while `dask-ec2 destroy` terminates instances it leaves volumes running?  This might result in unexpected costs to users.  If this is the case is there a robust way to terminate volumes as well?

**Comment by koverholt** [comment]
The AMI that is specified will have a default `Delete on Termination` setting, but it might also be possible to specify this to always be true by default? We do this for a [specific device here](https://github.com/dask/dask-ec2/blob/master/dask_ec2/ec2.py#L228), but I'm not sure this can be generalized to any device for any AMI.

**Comment by mrocklin** [comment]
OK, good to know.  Thanks for clarifying @koverholt
