### ISSUE TITLE
Turn off the dask-scheduler

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ec2#85]
Sometimes I want to kill the dask-scheduler process on the head node so that I can run my own (slightly modified).  When I kill the process it comes back fairly quickly.  Is there a way to kill this resurrection behavior temporarily?

**Comment by quasiben** [comment]
something like:

`supervisorctl -c /etc/supervisor/supervisord.conf stop dask-scheduler `

should work if executed on the head node

**Comment by mrocklin** [comment]
Worked like a charm.  Thanks @quasiben

**Comment by mrocklin** [comment]
Note to future self, the same works for the jupyter notebook with the following command:

    supervisorctl -c /etc/supervisor/supervisord.conf stop jupyter-notebook
