### ISSUE TITLE
Specify number of threads

### ISSUE THREAD

**Issue by lalitkumarj** [dask/dask-ec2#88]
On the dask-distributed efficiency page, it is recommended that many applications set --nthreads 1 when running dask-worker. Is there plans to expose --nthreads as an input parameter? It should be a relatively easy change on the salt state files?

Here is a link for reference, go to the section "Adjust between Threads and Processes".
https://distributed.readthedocs.io/en/latest/efficiency.html

**Comment by Chrisjw42** [comment]
Please can you advise on how to set this parameter on all workers at once, when using kubectl to manage a cluster?

**Comment by mrocklin** [comment]
The dask-ec2 project is retired.  Closing.  It sounds like you are asking a question about how to launch things with kubernetes or helm?  

If you're using helm (recommended) then I recommend looking at the helm configuration.
