### ISSUE TITLE
dask-ec2 versus dec2

### ISSUE THREAD

**Issue by mynameisvinn** [dask/dask-ec2#94]
what exactly is the difference between dask-ec2 and [dec2](http://matthewrocklin.com/blog/work/2016/03/16/dask-distributed-part-4)? both seem to accomplish the same things, so the distinction isn't clear to me!

**Comment by mrocklin** [comment]
dec2 is an old name.  I don't recommend trusting blogposts to be
authoritative.

**Comment by mynameisvinn** [comment]
thats what i figured... thanks @mrocklin!
